apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.hosts }}
        - {{ . }}
        {{- end }}

    {{- if .Values.certmanager.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        {{- range .Values.hosts }}
        - {{ . }}
        {{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.certmanager.secretName }}
    {{- end }}
